print('Задание 2.1')
print("=" * 28)
print("Привет")
print("друг")
print("=" * 28 + "\n")

print('Задание 2.2')
print("=" * 28)
print("||{:^24}||".format("Привет"))
print("||{:^24}||".format("друг"))
print("=" * 28 + "\n")

print('Задание 2.3')
print("=" * 28)
print("{: <14}{: >14}".format("||", "||"))
print("{: <14}{: >14}".format("||", "||"))
print("||{:^24}||".format("Привет"))
print("||{:^24}||".format("друг"))
print("{: <14}{: >14}".format("||", "||"))
print("{: <14}{: >14}".format("||", "||"))
print("=" * 28 + "\n")